service: telegram-bot

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  #stage: dev
  region: us-east-1
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:939077196930:table/subscribers"

functions:
  bot:
    handler: handler.bot
    memorySize: 128
    timeout: 5
    description: Main entrypoint for Telegram Webhook.
    events:
      - http:
          path: bot
          method: post
          cors: true
