service: telegram-bot


# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  #stage: dev
  region: us-east-1
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}

package:
  exclude:
    - docs
    - .travis.yml
    - .gitignore
    - .iml
    - example.env
    - README.md

functions:
  bot:
    handler: handler.bot
    memorySize: 64
    timeout: 5
    description: Main entrypoint for Telegram Webhook.
    events:
      - http:
          path: bot
          method: post
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline