version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Serverless CLI
          command: sudo npm install -g serverless
      - run:
          name: Change dirs
          command: cd services/sns-listener
      - run:
          name: Install app dependencies
          command: npm ci
      - run:
          name: Deploy application
          command: sls deploy
